language: rust

rust:
  - 1.34.0  # Oldest supported version
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_install:
  - sudo apt-get install -y libsensors4-dev

before_script:
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then rustup component add clippy; fi
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then rustup component add rustfmt; fi

script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then cargo clippy --all-targets --all-features -- -D warnings; fi
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then cargo fmt --all -- --check; fi
